### PR TITLE
Hw Settings Updates

### PR DESCRIPTION
**Pull request by evaesteban**
Fixes issues #16 and #21.

### CODE REVIEW

**Comment by retiutut** [comment]
This looks like EKG?  But it's in the "Setting up for EEG" doc?

Screen Shot 2020-11-24 at 4 46 19 PM

**Review by retiutut — CHANGES_REQUESTED** [review]
See above comment regarding new image and context.

**Review by shirleyzhang867 — APPROVED** [review]

**Comment by evaesteban** [comment]
You're right, I'll change it to EEG!

**Comment by retiutut** [comment]
@evaesteban Maybe we should consider having information on this in three docs:
- EEG setup
- EMG setup
- ECG setup

**Pull request closed without merging**
